CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS wallets (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  balance DECIMAL(10, 2) NOT NULL DEFAULT 1000000.00
);

INSERT IGNORE INTO users (username) VALUES
  ('12345678'),
  ('88888888');

INSERT IGNORE INTO wallets (user_id) VALUES
  (1),
  (2);

